/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiCountyAboutRouteImport } from './routes/api/county-about'
import { Route as ApiCrimeLiveRouteImport } from './routes/api/crime-live'
import { Route as ApiCrimeNamesRouteImport } from './routes/api/crime-names'
import { Route as ApiCrimeRefreshRouteImport } from './routes/api/crime-refresh'
import { Route as ApiDebtRouteImport } from './routes/api/debt'
import { Route as ApiFinanceNewsRouteImport } from './routes/api/finance-news'
import { Route as ApiFlightsRouteImport } from './routes/api/flights'
import { Route as ApiGateRouteImport } from './routes/api/gate'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiSorRouteImport } from './routes/api/sor'
import { Route as ApiWxRouteImport } from './routes/api/wx'
import { Route as ApiWxMapRouteImport } from './routes/api/wx-map'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountyAboutRoute = ApiCountyAboutRouteImport.update({
  id: '/api/county-about',
  path: '/api/county-about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrimeLiveRoute = ApiCrimeLiveRouteImport.update({
  id: '/api/crime-live',
  path: '/api/crime-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrimeNamesRoute = ApiCrimeNamesRouteImport.update({
  id: '/api/crime-names',
  path: '/api/crime-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrimeRefreshRoute = ApiCrimeRefreshRouteImport.update({
  id: '/api/crime-refresh',
  path: '/api/crime-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebtRoute = ApiDebtRouteImport.update({
  id: '/api/debt',
  path: '/api/debt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceNewsRoute = ApiFinanceNewsRouteImport.update({
  id: '/api/finance-news',
  path: '/api/finance-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlightsRoute = ApiFlightsRouteImport.update({
  id: '/api/flights',
  path: '/api/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGateRoute = ApiGateRouteImport.update({
  id: '/api/gate',
  path: '/api/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSorRoute = ApiSorRouteImport.update({
  id: '/api/sor',
  path: '/api/sor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWxRoute = ApiWxRouteImport.update({
  id: '/api/wx',
  path: '/api/wx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWxMapRoute = ApiWxMapRouteImport.update({
  id: '/api/wx-map',
  path: '/api/wx-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/county-about': typeof ApiCountyAboutRoute
  '/api/crime-live': typeof ApiCrimeLiveRoute
  '/api/crime-names': typeof ApiCrimeNamesRoute
  '/api/crime-refresh': typeof ApiCrimeRefreshRoute
  '/api/debt': typeof ApiDebtRoute
  '/api/finance-news': typeof ApiFinanceNewsRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/gate': typeof ApiGateRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/sor': typeof ApiSorRoute
  '/api/wx': typeof ApiWxRoute
  '/api/wx-map': typeof ApiWxMapRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/county-about': typeof ApiCountyAboutRoute
  '/api/crime-live': typeof ApiCrimeLiveRoute
  '/api/crime-names': typeof ApiCrimeNamesRoute
  '/api/crime-refresh': typeof ApiCrimeRefreshRoute
  '/api/debt': typeof ApiDebtRoute
  '/api/finance-news': typeof ApiFinanceNewsRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/gate': typeof ApiGateRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/sor': typeof ApiSorRoute
  '/api/wx': typeof ApiWxRoute
  '/api/wx-map': typeof ApiWxMapRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/county-about': typeof ApiCountyAboutRoute
  '/api/crime-live': typeof ApiCrimeLiveRoute
  '/api/crime-names': typeof ApiCrimeNamesRoute
  '/api/crime-refresh': typeof ApiCrimeRefreshRoute
  '/api/debt': typeof ApiDebtRoute
  '/api/finance-news': typeof ApiFinanceNewsRoute
  '/api/flights': typeof ApiFlightsRoute
  '/api/gate': typeof ApiGateRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/news': typeof ApiNewsRoute
  '/api/sor': typeof ApiSorRoute
  '/api/wx': typeof ApiWxRoute
  '/api/wx-map': typeof ApiWxMapRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/alerts'
    | '/api/county-about'
    | '/api/crime-live'
    | '/api/crime-names'
    | '/api/crime-refresh'
    | '/api/debt'
    | '/api/finance-news'
    | '/api/flights'
    | '/api/gate'
    | '/api/geocode'
    | '/api/markets'
    | '/api/news'
    | '/api/sor'
    | '/api/wx'
    | '/api/wx-map'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/alerts'
    | '/api/county-about'
    | '/api/crime-live'
    | '/api/crime-names'
    | '/api/crime-refresh'
    | '/api/debt'
    | '/api/finance-news'
    | '/api/flights'
    | '/api/gate'
    | '/api/geocode'
    | '/api/markets'
    | '/api/news'
    | '/api/sor'
    | '/api/wx'
    | '/api/wx-map'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/alerts'
    | '/api/county-about'
    | '/api/crime-live'
    | '/api/crime-names'
    | '/api/crime-refresh'
    | '/api/debt'
    | '/api/finance-news'
    | '/api/flights'
    | '/api/gate'
    | '/api/geocode'
    | '/api/markets'
    | '/api/news'
    | '/api/sor'
    | '/api/wx'
    | '/api/wx-map'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiCountyAboutRoute: typeof ApiCountyAboutRoute
  ApiCrimeLiveRoute: typeof ApiCrimeLiveRoute
  ApiCrimeNamesRoute: typeof ApiCrimeNamesRoute
  ApiCrimeRefreshRoute: typeof ApiCrimeRefreshRoute
  ApiDebtRoute: typeof ApiDebtRoute
  ApiFinanceNewsRoute: typeof ApiFinanceNewsRoute
  ApiFlightsRoute: typeof ApiFlightsRoute
  ApiGateRoute: typeof ApiGateRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiSorRoute: typeof ApiSorRoute
  ApiWxRoute: typeof ApiWxRoute
  ApiWxMapRoute: typeof ApiWxMapRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/county-about': {
      id: '/api/county-about'
      path: '/api/county-about'
      fullPath: '/api/county-about'
      preLoaderRoute: typeof ApiCountyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crime-live': {
      id: '/api/crime-live'
      path: '/api/crime-live'
      fullPath: '/api/crime-live'
      preLoaderRoute: typeof ApiCrimeLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crime-names': {
      id: '/api/crime-names'
      path: '/api/crime-names'
      fullPath: '/api/crime-names'
      preLoaderRoute: typeof ApiCrimeNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crime-refresh': {
      id: '/api/crime-refresh'
      path: '/api/crime-refresh'
      fullPath: '/api/crime-refresh'
      preLoaderRoute: typeof ApiCrimeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debt': {
      id: '/api/debt'
      path: '/api/debt'
      fullPath: '/api/debt'
      preLoaderRoute: typeof ApiDebtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance-news': {
      id: '/api/finance-news'
      path: '/api/finance-news'
      fullPath: '/api/finance-news'
      preLoaderRoute: typeof ApiFinanceNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flights': {
      id: '/api/flights'
      path: '/api/flights'
      fullPath: '/api/flights'
      preLoaderRoute: typeof ApiFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gate': {
      id: '/api/gate'
      path: '/api/gate'
      fullPath: '/api/gate'
      preLoaderRoute: typeof ApiGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sor': {
      id: '/api/sor'
      path: '/api/sor'
      fullPath: '/api/sor'
      preLoaderRoute: typeof ApiSorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wx': {
      id: '/api/wx'
      path: '/api/wx'
      fullPath: '/api/wx'
      preLoaderRoute: typeof ApiWxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wx-map': {
      id: '/api/wx-map'
      path: '/api/wx-map'
      fullPath: '/api/wx-map'
      preLoaderRoute: typeof ApiWxMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiCountyAboutRoute: ApiCountyAboutRoute,
  ApiCrimeLiveRoute: ApiCrimeLiveRoute,
  ApiCrimeNamesRoute: ApiCrimeNamesRoute,
  ApiCrimeRefreshRoute: ApiCrimeRefreshRoute,
  ApiDebtRoute: ApiDebtRoute,
  ApiFinanceNewsRoute: ApiFinanceNewsRoute,
  ApiFlightsRoute: ApiFlightsRoute,
  ApiGateRoute: ApiGateRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiMarketsRoute: ApiMarketsRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiSorRoute: ApiSorRoute,
  ApiWxRoute: ApiWxRoute,
  ApiWxMapRoute: ApiWxMapRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
